swagger: '2.0'
info:
  title: My API
  description: My Flask API documentation
  version: '1.0'
paths:
  /:
    get:
      summary: Says Hello
      responses:
        200:
          description: String Response
          schema:
            type: str
            properties:
              data:
                type: string